version: 3

tasks:
  default:
    cmds:
      - task: run_debug

  test:
    cmds:
      - odin test src/aoc24 -out=build/aoc24-test -o:none -debug -strict-style
    aliases:
      - t
    method: none
    silent: true
    sources:
      - ./src/aoc24/**/*.odin

  build_debug:
    aliases:
      - b
    cmds:
      - odin build src/aoc24 -out=build/aoc24-debug -o:none -debug -strict-style
    silent: true
    sources:
      - ./src/aoc24/**/*.odin
    generates:
      - ./build/aoc24-debug

  build_release:
    aliases:
      - release
      - rel
    cmds:
      - odin build src/aoc24 -out=build/aoc24 -o:aggressive -vet -strict-style
    silent: true
    sources:
      - ./src/aoc24/**/*.odin
    generates:
      - ./build/aoc24

  run_debug:
    aliases:
      - r
      - run
    deps:
      - build_debug
    silent: true
    cmds:
      - build/aoc24-debug
    method: none

  run_release:
    aliases:
      - rr
      - run-rel
      - run-release
    deps:
      - build_release
    silent: true
    cmds:
      - build/aoc24
    method: none

interval: 250ms
